### ISSUE TITLE
Using @import

### ISSUE THREAD

**Issue by meleyal** [brunch/sass-brunch#1]
To share variables/mixins between files with sass you need to use an `@import`. E.g. in `app.scss` you might have:

```
@import 'variables';
@import 'mixins';
@import 'base';
@import 'layout';
...
```

Is there any way to tell Brunch just to include the `app.scss` file (the 'manifest') and let sass handle combining the files?

I already tried this in `config.coffee`:

```
stylesheets:
  defaultExtension: 'scss'
  joinTo:
    'stylesheets/app.css': /^styles\/app/
```
