### ISSUE TITLE
Cannot pass CLI arguments to compass compiler

### ISSUE THREAD

**Issue by abobwhite** [brunch/sass-brunch#54]
I am trying to nestle in development vs. production options in my compass config file and I need to pass compass command line arguments telling it which environment to use when compiling.

I've made a bit of progress figuring how to trigger different environments from the CLI with brunch using --env <environment> and specifying `overrides` sections in my config.coffee. I'm passing arguments per the compass documentation here: http://compass-style.org/help/tutorials/configuration-reference/ in the "Inspecting Configuration Settings passed via the Command Line" section.

```
overrides:
    development:
      plugins:
        sass:
          options: ['-e', 'development', '--force']
    production:
      plugins:
        sass:
          options: ['-e', 'production', '--force']

  plugins:
    sass:
      options: ['--compass']
      mode: 'ruby'
```

Now when I try to build, though, it doesn't appear to like the parameters I'm trying to pass to compass. I'm getting this error:

```
C:\Git\myProject>brunch build --env development
29 May 16:04:51 - error: Compiling of 'app\sass\header.scss' failed. C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.3.7/lib/sass/exec.rb:41:in `parse': invalid option: -e (OptionParser::InvalidOption)
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.3.7/lib/sass/exec.rb:22:in `parse!'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.3.7/bin/sass:13:in `<top (required)>'
        from C:/Ruby200/bin/sass:23:in `load'
        from C:/Ruby200/bin/sass:23:in `<main>'
```

Any idea why passing this argument isn't getting through to Compass?

UPDATE:
If I remove `mode: 'ruby'`, it compiles with no error, but is not using the compass configuration at all.
