### ISSUE TITLE
Strange Behavior 

### ISSUE THREAD

**Issue by hyyan** [brunch/sass-brunch#63]
I am trying to use compass with this plugin but I keep getting strange behavior when compass is involved 

Some configs is read from `config.rb` while other is ignored 

here is my `config.rb` file:

```
add_import_path "bower_components/bootstrap-sass-official/assets/stylesheets"
require 'compass/import-once/activate'
# Require any additional compass plugins here.


# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "public/css"
images_dir = "public/images"
javascripts_dir = "public/js"
fonts_dir = "public/fonts"


# You can select your preferred output style here (can be overridden via the command line):
output_style = :compressed

# To enable relative paths to assets via compass helper functions. Uncomment:
relative_assets = false

# To disable debugging comments that display the original location of your selectors. Uncomment:
line_comments = true

# If you prefer the indented syntax, you might want to regenerate this
# project again passing --syntax sass, or you can uncomment this:
# preferred_syntax = :sass
# and then run:
# sass-convert -R --from scss --to sass sass scss && rm -rf sass && mv scss sass

```

Now the following configs is read:

```
add_import_path "bower_components/bootstrap-sass-official/assets/stylesheets"
require 'compass/import-once/activate'
# Require any additional compass plugins here.


# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "public/css"
images_dir = "public/images"
javascripts_dir = "public/js"
fonts_dir = "public/fonts"
```

And the rest of file is ignored ?!

Here is my brunch config file :

```
exports.config =
  # See http://brunch.io/#documentation for docs. 
  paths:
    public: 'public'

  plugins:
    autoReload:
      enabled: true
    sass:
      options: ['--compass']
  files:
    javascripts:
      joinTo:
        'js/app.js': /^(app[\\/]scripts)/
        'js/vendor.js': /^(vendor|bower_components)/

    stylesheets:
      joinTo: 
        'css/app.css': /^((app[\\/]styles(?!-rtl))|bower_components|vendor)/
        'css/app-rtl.css': /^(app[\\/]styles-rtl)/

  modules:
     wrapper: false
     definition: false

  conventions:
     # we don't want javascripts in asset folders to be copied like the one in 
     # the bootstrap assets folder
     assets: /assets[\\/](?!javascripts)|bower_components[\\/]bootstrap-rtl[\\/]dist/

  # this option will disable sass --debug-info option
  minify: true


```

Any idea ? Thanks
